{% set name = "databricks-cli" %}
{% set version = "0.17.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d5ef6520ea3ed403d58f24538641bd8eeb163621f5054205fcf643578698579

build:
  number: 0
  entry_points:
    - databricks=databricks_cli.cli:cli
    - dbfs=databricks_cli.dbfs.cli:dbfs_group
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - click >=7.0
    - configparser >=0.3.5
    - oauthlib >=3.1.0
    - python >=3.6
    - pyjwt >=1.7.0
    - requests >=2.17.3
    - six >=1.10.0
    - tabulate >=0.7.7
    - urllib3 >=1.26.7,<2.0.0

test:
  requires:
    - pip
  imports:
    - databricks_cli
    - databricks_cli.cluster_policies
    - databricks_cli.clusters
    - databricks_cli.configure
    - databricks_cli.dbfs
    - databricks_cli.groups
    - databricks_cli.jobs
    - databricks_cli.libraries
    - databricks_cli.oauth
    - databricks_cli.pipelines
    - databricks_cli.repos
    - databricks_cli.runs
    - databricks_cli.sdk
    - databricks_cli.secrets
    - databricks_cli.stack
    - databricks_cli.tokens
    - databricks_cli.unity_catalog
    - databricks_cli.workspace
  commands:
    - databricks --help
    - dbfs --help
    - pip check

about:
  home: https://github.com/databricks/databricks-cli
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A command line interface for Databricks
  dev_url: https://github.com/databricks/databricks-cli

extra:
  recipe-maintainers:
    - thewchan
    - andrewmchen
    - jaroslawk
    - oblute
