{% set name = "databricks-cli" %}
{% set version = "0.218.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/databricks/cli/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c8715e3fa28bf4e637bcc5de8116b345668884230bee742029e20ae5af123243

build:
  number: 0
  script_env:
    - BINARY_FILEPATH={{ PREFIX }}/bin/databricks      # [not win]
    - BINARY_FILEPATH={{ PREFIX }}/bin/databricks.exe  # [win]

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses
    - posix                  # [win]

test:
  requires:
    - ripgrep
  commands:
    - databricks --help
    - databricks --version | rg {{ version }}

about:
  summary: A command line interface for Databricks
  home: https://github.com/databricks/cli
  license: LicenseRef-Databricks-License
  license_file:
    - LICENSE
    - NOTICE
    - thirdparty/

extra:
  recipe-maintainers:
    - thewchan
    - andrewmchen
    - jaroslawk
    - oblute
    - dhirschfeld
