{% set name = "databricks-cli" %}
{% set version = "0.215.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/databricks/cli/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f84c554145c7ac9dee3ff0ca7dd39367a415ca7eb4d6a110fa7fc1c21e2cc282

build:
  number: 0
  skip: true  # [not linux]
  script: |
    set -exuo pipefail
    export CGO_ENABLED=0
    go mod vendor
    go build \
      -trimpath \
      -mod vendor \
      -ldflags "-X github.com/databricks/cli/internal/build.buildVersion={{ version }}" \
      -o "${PREFIX}/bin/databricks"
    # Clear out cache to avoid file not removable warnings
    chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses

test:
  commands:
    - databricks --help
    - databricks --version | grep {{ version }}

about:
  summary: A command line interface for Databricks
  home: https://github.com/databricks/cli
  license: LicenseRef-Databricks-License
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - thewchan
    - andrewmchen
    - jaroslawk
    - oblute
    - dhirschfeld
